name: NMAP Nexus Signal
on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:  # Activation manuelle
  push:  # À chaque modification

jobs:
  emit_signal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Run Nexus Signal
        run: |
          echo "🚀 Démarrage du Nexus Signal..."
          python nexus.py
          echo "✨ Signal émis avec succès"
          
      - name: Commit Changes
        run: |
          git config --global user.name 'ASuperIntelligenceSOS'
          git config --global user.email 'ASuperIntelligenceSOS@users.noreply.github.com'
          git add manifest.json
          git commit -m "📡 Signal Nexus émis [$(date)]" || echo "Pas de changements"
          git push
